## Jupyter Notebook とは

webブラウザから使用できるインタラクティブなプログラムの実行環境
1. セル単位でプログラムを実行できる
2. インタラクティブに結果の可視化が行える
3. markdown記法にも対応していて，文書からコード，その実行結果まで一つのファイルで管理できる

In [2]:
print("Hello, world!")

Hello, world!


## Python の文法について

### 変数

- C言語では宣言文によって，変数のデータ型と名前を定義する必要がある. 例) `int x = 3;`
- pythonでは，変数に値を代入したタイミングで変数が定義される (型宣言をする必要がない)

In [3]:
x = 3
print(x)

3


In [4]:
# #でコメントアウトできる
# print文を書かなくても， セルの最後の行の変数や計算結果の値を確認できる
x + 3

6

#### 変数の型

- int型 (整数)
- float型 (浮動小数点型)
- str型 (文字列型)
- bool型 (真偽値)

In [5]:
i = 4
print(type(i))

<class 'int'>


In [6]:
f = 2.1
print(type(f))

<class 'float'>


In [7]:
s = "Hello, world!"  # クオーテーションで囲う
print(type(s))

<class 'str'>


In [8]:
b = True
print(type(b))

<class 'bool'>


#### 特殊な文字列

- エスケープシーケンス
- f文字列
- r文字列

In [9]:
# \nで改行，\tでタブ
print("Hello\n\tWorld!")

Hello
	World!


In [10]:
# r""でエスケープシーケンス等をそのまま出力
print(1, r"Hello\n\tWorld!")
print(2, r"C:\Users\E\test")

1 Hello\n\tWorld!
2 C:\Users\E\test


In [11]:
# f"{変数}"で文字列中に変数を代入
var = 1.23
print(f"var is {var}")

var is 1.23


### 演算子

- 代数演算子
- 代入演算子
- 文字列演算

### 演算子
#### 代数演算子

- `+` 加算
- `-` 減算
- `*` 乗算
- `/` 除算
- `**` 冪乗
- `%` 余りを計算
- `//` 切り捨て

In [12]:
# 加算
print("2 + 3 =", 2 + 3)
# 減算
print("2 - 3 =", 2 - 3)
# 乗算
print("2 * 3 =", 2 * 3)
# 除算
print("2 / 3 =", 2 / 3)

2 + 3 = 5
2 - 3 = -1
2 * 3 = 6
2 / 3 = 0.6666666666666666


In [13]:
# 冪乗
print("2 ** 3 =", 2 ** 3)
# 余り
print("2 %  3 =", 2 % 3)
# 切り捨て
print("2 // 3 =", 2 // 3)

2 ** 3 = 8
2 %  3 = 2
2 // 3 = 0


#### 代入演算子

- `a = b`
  - aにbを代入
- `a += b`
  - `a = a + b` と同じ
- `a -= b`
  - `a = a - b` と同じ
- `a *= b`
  - `a = a * b` と同じ
- `a /= b`
  - `a = a / b` と同じ

In [14]:
a = 3
a = a + 3
print(a)
a += 3
print(a)

6
9


#### 文字列演算

- `+` 文字列の連結
- `*` 文字列を定数回繰り返す

In [15]:
s1 = "Hello, "
s2 = "world! "
s = s1 + s2
print(s)

Hello, world! 


In [16]:
print(s * 3)

Hello, world! Hello, world! Hello, world! 


### 複合データ型

複数のデータをまとめて扱う
- `list`: リスト
- `tuple`: タプル
- `dict`: 辞書

#### リスト

`[]`の中に複数の変数を`,`で区切って格納したもの

In [17]:
# リストを定義
numbers = [1, 2, 3, 4, 5]
print(numbers)

[1, 2, 3, 4, 5]


In [18]:
# 要素数の確認
print(len(numbers))

5


In [19]:
# list[インデックス] で各要素にアクセスできる
# 先頭が0から始まることに注意
print(numbers[0])

1


In [20]:
# インデックスを負の値にすると末尾からの位置になる
print(numbers[-1])

5


In [21]:
# 範囲外のインデックスを指定するとエラー
# pythonはエラー文が親切なので，しっかり読もう
print(numbers[100])

IndexError: list index out of range

In [22]:
# スライスを用いることで， リストから複数の値を取り出すことも
# list[開始位置:終了位置(:ステップ)]
print(1, numbers[1:3])
print(2, numbers[0:5:2])

1 [2, 3]
2 [1, 3, 5]


In [23]:
# 先頭や末尾のインデックスは省略できる
print(1, numbers[:3]) # numbers[0:3] と同じ
print(2, numbers[3:]) # numbers[3:5] と同じ
print(3, numbers[:])  # numbers[0:5] と同じ

1 [1, 2, 3]
2 [4, 5]
3 [1, 2, 3, 4, 5]


In [24]:
# 逆順に表示することも
print(numbers[::-1]) # numbers[-1:-6:-1] と同じ

[5, 4, 3, 2, 1]


In [25]:
# 要素を追加
numbers.append(6)
print(numbers)

[1, 2, 3, 4, 5, 6]


In [26]:
# 2次元配列
numbers_2d = [[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]
print(numbers_2d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


#### タプル

`()`の中に複数の変数を`,`区切りで格納したもの  
リストとの違いとして，一度定義したタプルは中身を変更することができない

In [27]:
assistants = ("nojima", "kohyama", "manabe")

In [28]:
# リストと同様に tuple[インデックス] で各要素にアクセスできる
print(assistants[0])

nojima


In [29]:
# タプルは途中で中身を変更できない
assistants[0] = "aoki"

TypeError: 'tuple' object does not support item assignment

#### 辞書型

キーとそれに対応する値を組み合わせて格納できる.  
`{key: value}`の形で書く.

In [30]:
grades = {"signal processing": "A",
          "LSI": "C",
          "Informatics engineering": "S"}

In [31]:
# dict[key] で値を参照できる
print(grades["signal processing"])

A


In [32]:
# dict.get(key) でも値を参照できる
print(grades.get("signal processing"))

A


In [33]:
# 無いキーを指定した場合の動作が異なる
print(1, grades.get("computer vision")) # None
print(2, grades["computer vision"]) # Raise KeyError

1 None


KeyError: 'computer vision'

In [34]:
# 値を入れ直すこともできる
grades["LSI"] = "D"
print(grades["LSI"])

D


In [35]:
# dict.keys() キーの一覧を取り出す
print(grades.keys())

dict_keys(['signal processing', 'LSI', 'Informatics engineering'])


In [36]:
# dict.values() 値の一覧を取り出す
print(grades.values())

dict_values(['A', 'D', 'S'])


In [37]:
# dict.items() キーと値の二つを取り出す
print(grades.items())

dict_items([('signal processing', 'A'), ('LSI', 'D'), ('Informatics engineering', 'S')])


### 制御構文

- 条件分岐 ([`if`/`else`/`elif`](#41-if文))
- 繰り返し ([`for`](#42-for文)/[`while`](#43-while文))

pythonはインデント記法を採用しているため, 
`:`とインデント(スペース)を用いてこれらの処理を書く．

```python
if 条件式:
    なんらかの処理
```

#### if文

条件を満たしたかどうか(`True` or `False`)で処理を変えるための構文

```python
if 条件1:
    処理1  # 条件1を満たした時
elif 条件2:
    処理2  # 条件1を満たしていなく，かつ条件2を満たした時
else:
    処理3  # 条件1も条件2も満たしていない時
```


条件式の書き方．比較演算子とブール演算子を組み合わせて書く．
- 比較演算子
  - `a == b`: aとbが等しい 
  - `a != b`: aとbが異なる
  - `a < b`: aがbよりも小さい
  - `a > b`: aがbよりも大きい
  - `a >= b`: aがb以上
  - `a <= b`: aがb以下
  - `a in b`: aがbに含まれる
- ブール演算子
  - `A and B`: AとBが真なら真
  - `A or B`: AかBが真なら真
  - `not A`: Aが偽なら真

In [38]:
# 条件式
print(1, 10 > 5)
print(2, "123" == 123)

1 True
2 False


In [39]:
# xの大きさを判断する
x = 10
if x >= 100:
    print("Too large")
elif x > 50:
    print("Large")
elif x == 50:
    print("Bingo!")
elif 10 <= x and x < 50:
    print("Small")
else:
    print("Too small")

Small


In [40]:
# 10 <= x and x < 50 の書き換え
x = 30
if 10 <= x < 50:
    print("True")

True


In [41]:
# in 演算子
x = 5
numbers = [1, 2, 3, 4, 5]
if x in numbers:
    print("True")
else:
    print("False")

True


条件式は`True`/`False`の2値を返すものが基本だが，Pythonでは以下の要素はFalse，他はTrueとみなされため，変数を条件式として用いることもできる．

Falseとみなされる例
- `False`
- ゼロ(`0`, `0.0`)
- 空文字列(`""`)
- 空の複合データ(`[]`, `()`, `{}`)
- None

In [42]:
# 出力を予想してみよう
for item in [0, 1, 0.0, "abc", "", [1, 2 ,3], None]:
    if not item:
        print(item)

0
0.0

None


#### for文

イテラブルオブジェクト(反復可能なオブジェクト)を用いた構文．  
listなどもイテラブルオブジェクトになる．
`range()`という組み込みの関数を使うと，  
指定した回数分の整数をもつイテラブルオブジェクトを作ってくれる
```python
for 変数 in イテラブルオブジェクト:
    なんらかの処理
```

In [43]:
# リストの要素を一つずつ取り出す
for i in [0, 1, 2, 3, 4]:
    print(i)

0
1
2
3
4


In [44]:
# range()関数を使うと，リストを手書きする必要がない
for i in range(5):
    print(i)

0
1
2
3
4


In [45]:
# (開始位置, 終了位置(, ステップ))も指定することができる
for i in range(10, 30, 5):
    print(i)

10
15
20
25


In [46]:
# タプルもイテラブルオブジェクト
prime_numbers = (2, 3, 5, 7, 11)
for n in prime_numbers:
    print(n)

2
3
4
7
11


In [47]:
# rangeを使ってイテラブルの中身を取り出すこともできる
N = len(prime_numbers)
for i in range(N):
    print(prime_numbers[i])

2
3
4
7
11


In [48]:
# 二重リスト
numbers_2d = [[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]

# 要素を取得
for numbers_1d in numbers_2d:
    print(numbers_1d)

for a, b, c in numbers_2d:
    print(b)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
2
5
8


In [49]:
# 二重ループ
for numbers_1d in numbers_2d:
    for i in numbers_1d:
        print(i)

1
2
3
4
5
6
7
8
9


In [50]:
# dict.keys(), dict.values(), dict.items() もイテラブルオブジェクトを返している
grades = {"signal processing": "A",
          "LSI": "C",
          "Informatics engineering": "S"}
for key in grades.keys():
    print(key)

signal processing
LSI
Informatics engineering


In [51]:
for val in grades.values():
    print(val)

A
C
S


In [52]:
for key, val in grades.items():
    print(key, val)

signal processing A
LSI C
Informatics engineering S


#### while文

条件を満たしている間，ループし続ける．  
適切に条件を指定したり，終了条件を定めないと無限ループしてしまう
```python
while 条件式:
    処理
```

In [53]:
x = 0
while x < 5:
    x += 1
    print(x)

1
2
3
4
5


In [54]:
# 無限にループしてしまう！！
# notebookの停止ボタンで，セル内の処理を止めることができる
x = 0
while True:
   x += 1

KeyboardInterrupt: 

In [55]:
# break 文を使ってループを抜けることができる
# whileやforの先頭に戻るcontinue文もある
x = 0
while True:
    x += 1
    if x >= 100:
        break
print(x)

100


In [56]:
# continue文の例
# 出力を予想してみよう
x = 0
y = 0
while True:
    x += 1

    if x % 3 != 0:
        continue

    y += 1

    if x >= 10:
        break

print("x:", x)
print("y:", y)

x: 12
y: 4


#### 演習 FizzBuzz問題を解いてみよう

1から100までの数字を画面に表示する．  
その際に，数字が3の倍数の時は，数字の代わりに "Fizz"と出力する．
同様に5の倍数の時は，"Buzz"と出力し，
3の倍数でもあり5の倍数でもある時は"FizzBuzz"と出力しよう．


**期待する出力**
```
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
```

In [1]:
# ここにコードを記入
for i in range(100):
    i+=1
    match i:
        case i if i % 3 == 0 and i % 5 == 0:
            print("FizzBuzz")
        case i if i % 3 == 0:
            print("Fizz")
        case i if i % 5 == 0:
            print("Buzz")
        case _:
            print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


### 関数の定義
`def`を用いて関数を定義する．  
関数も`:`とインデントを用いる．
```python
def func(引数):
    処理
```

In [58]:
# 関数を定義
def double(x):
    print(2 * x)

In [59]:
# 関数を実行
double(10)

20


In [60]:
# 引数を複数指定することもできる
def add(x, y):
    print(x + y)

In [61]:
add(3, 2)

5


In [62]:
# 返り値は return で返すことができる
def add(x, y):
    return x + y

In [63]:
result = add(10, 20)
print(result)

30


### クラス

例えば，青木研究室のメンバーの名簿を作ることを考える．  
それぞれのメンバーには苗字，名前，メールの情報を入れたい．
愚直に実装すると
```python
professors = [
    {"first_name": "Yoshimitsu", "last_name": "Aoki", "email": "aoki@elec.keio.ac.jp"},
    {"first_name": "Masahiro", "last_name": "Yukawa", "email": "yukawa@elec.keio.ac.jp"},
    {"first_name": "Masaaki", "last_name": "Ikehara", "email": "ikehara@tkhm.elec.keio.ac.jp"},
]
```

となるが，各メンバーを構成する要素は同じ．  
-> 共通の設計図(クラス)を作ってあげると，各メンバーに属している変数(属性)や共通の振る舞い(メソッド)をもつ，メンバー(インスタンス)を作るのが簡単になる．

In [64]:
# クラスを定義
class Member:
    # インスタンス化する時に呼び出される関数
    # selfはインスタンス自身を表す
    def __init__(self, first_name, last_name, email):
        self.first_name = first_name
        self.last_name = last_name
        self.email = email

In [65]:
aoki = Member(first_name="Yoshimitsu",
              last_name="Aoki",
              email="aoki@elec.keio.ac.jp")
print(1, aoki.first_name) # __init__で初期化されたself.first_nameを参照
print(2, aoki.email)

1 Yoshimitsu
2 aoki@elec.keio.ac.jp


In [66]:
# クラスを定義
class Member:
    # インスタンス化する時に呼び出される関数
    # selfはインスタンス自身を表す
    def __init__(self, first_name, last_name, email):
        self.first_name = first_name
        self.last_name = last_name
        self.email = email

    def self_introduction(self):
        print("Hi, there! I'm", self.first_name, self.last_name)

In [67]:
aoki = Member(first_name="Yoshimitsu",
              last_name="Aoki",
              email="aoki@elec.keio.ac.jp")
aoki.self_introduction()

Hi, there! I'm Yoshimitsu Aoki


In [68]:
yukawa = Member(first_name="Masahiro",
                   last_name="Yukawa",
                   email="yukawa@elec.keio.ac.jp")
yukawa.self_introduction()

Hi, there! I'm Masahiro Yukawa


## 外部モジュール
講義中に扱う多い外部モジュールの使い方

### numpy

高速に配列計算を行うためのライブラリ
- 配列の作成
- 要素の取得
- 配列の計算
- ブロードキャスト
- numpy配列とif
- np.where()
- Pythonの配列との違い

In [69]:
# ライブラリをインポート. numpyはnpとして扱うのが慣例
import numpy as np

#### 配列の作成

In [70]:
# 1次元配列を作る
# np.array にリストを入れることで，1次元配列を定義できる
arr = np.array([1, 2, 3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [71]:
# np.arange()でrange風の配列を作る
# np.arange(要素数)，またはnp.arange(初期値, 終了条件(, ステップ))
print(1, np.arange(5))
print(2, np.arange(4, 7))

1 [0 1 2 3 4]
2 [4 5 6]


In [72]:
# 二次元配列を定義
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])
print(arr_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [73]:
# 形状を表示
print(arr_2d.shape)

(4, 3)


#### 要素の取得

In [74]:
# インデックスを指定することで配列の一部を取り出せる
print(arr[0])

1


In [75]:
# 二次元配列の1行目を取り出す
print(arr_2d[0])

[1 2 3]


In [76]:
# 二次元配列の1列目を取り出す
# [:]は[0:-1]の省略で，全行を取得する
print(arr_2d[:, 0])

[ 1  4  7 10]


In [77]:
# 2行3列目を取り出す
print(arr_2d[1, 2])
print(arr_2d[1][2])

6
6


#### 配列の計算

In [78]:
# 配列の宣言
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([arr1, arr2])
arr4 = np.array([arr2, arr1])

In [79]:
# 一次元配列の計算
print("足し算: ", arr1 + arr2)
print("引き算: ", arr1 - arr2)
print("直積: ", arr1 * arr2)
print("内積: ", np.dot(arr1, arr2))

足し算:  [5 7 9]
引き算:  [-3 -3 -3]
直積:  [ 4 10 18]
内積:  32


In [80]:
# 二次元配列の計算
print("足し算:\n", arr3 + arr4)
print("引き算:\n", arr3 - arr4)
print("直積:\n", arr3 * arr4)

足し算:
 [[5 7 9]
 [5 7 9]]
引き算:
 [[-3 -3 -3]
 [ 3  3  3]]
直積:
 [[ 4 10 18]
 [ 4 10 18]]


In [81]:
# arr3 の列数と， arr4の行数が一致していないと内積は計算できない
# error!
np.dot(arr3, arr4)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [82]:
# 転置をしてから内積を取る
print(arr4.shape)
arr4_t = arr4.T
print(arr4_t.shape)

(2, 3)
(3, 2)


In [83]:
print(np.dot(arr3, arr4_t))

[[32 14]
 [77 32]]


#### ブロードキャスト

異なる形状の配列を計算する際に，一定のルールに基づいて形状が同じになるように自動で変換してくれる機能

具体的には以下のようなルールで実行される
- 次元数を揃える
  2つの配列の次元数が異なる場合、次元数が少ない方の配列の先頭にサイズ（長さ）が1の新しい次元を追加して次元数を揃える。
- 各次元のサイズ（長さ）を揃える
  2つの配列の各次元のサイズが一致しない場合、サイズが1である次元は他方の配列の次元のサイズに引き伸ばされる（値が繰り返される）。
- 2つの配列のどちらのサイズも1ではない次元が存在するとブロードキャストできずにエラーとなる。

In [84]:
arr5 = np.array([1, 2, 3])
arr6 = np.array([[5, 6, 7],
                 [8, 9, 10]])

In [85]:
arr5 * 10

array([10, 20, 30])

In [86]:
arr5 * arr6

array([[ 5, 12, 21],
       [ 8, 18, 30]])

In [87]:
# ブロードキャストできない例
# error!
arr7 = np.array([2, 3])
arr5 * arr7

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

#### numpy配列とif

numpy配列を比較する場合，各要素に対する比較の結果(`True`/`False`)がnumpy配列として出力される．numpy配列を直接if文の条件式として扱うことはできず，`arr.all()`や`arr.any()`を用いる．

In [88]:
arr8 = np.array([1, 2, 3])
arr9 = np.array([1, 2, 3])
arr10 = np.array([1, 2, 4])

In [89]:
print(1, arr8 == arr9)
print(2, arr8 == arr10)
print(3, arr8 == 2) # ブロードキャストにより
print(4, arr8 < 2)  # np.array([2, 2, 2])と比較される

1 [ True  True  True]
2 [ True  True False]
3 [False  True False]
4 [ True False False]


In [90]:
# エラー: numpy配列を直接ifの条件式とすることはできない
if (arr8 == arr9):
    print("arr8 is equal to arr9")
else:
    print("else")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [91]:
# anyやallの利用
print(1, (arr8 == arr9).all())
print(2, (arr8 == arr10).all())
print(3, (arr8 == arr10).any())

1 True
2 False
3 True


In [92]:
if (arr8 == arr9).all():
    print("arr8 is equal to arr9")

arr8 is equal to arr9


#### np.where()

指定した条件を満たす配列内の要素のインデックスを見つけたり、特定の条件を満たす要素に新しい値を割り当てたりするのに利用する

In [93]:
# 例: 1次元配列での利用
arr_1d = np.array([1, 2, 3, 4, 5])
print(np.where(arr_1d > 2))

(array([2, 3, 4]),)


In [94]:
# 例: 2次元配列での利用
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d)
print(np.where(arr_2d > 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))


In [95]:
# 特定の条件を満たす要素に新しい値を割り当てる例
new_arr = np.where(arr > 4, 100, arr)
print(new_arr)

[1 2 3]


In [96]:
# マスクの利用
mask = np.array([1, 1, 1, 0, 0, 0])
arr11 = np.array([11, 22, 33, 44, 55, 66])
arr12 = np.array([-12, -24, -36, -48, -60, -72])
masked = np.where(mask, arr11, arr12)
print(masked)

[ 11  22  33 -48 -60 -72]


#### Pythonの配列とnumpyの配列の扱い方の違いの例

In [97]:
pi = [3, 1, 4]
pi_np = np.array(pi)

- 配列の比較

In [98]:
# Pythonの配列の比較
print(pi == pi)

True


In [99]:
# numpy配列の比較
print("1", pi_np == pi_np)
print("2", (pi_np == pi_np).all())

1 [ True  True  True]
2 True


- 要素の追加

In [100]:
# Pythonの配列の末尾に一つ追加
pi.append(1)
# Pythonの配列の末尾に配列を追加
pi.extend([5, 9])
pi += [2, 6]
print(pi)

[3, 1, 4, 1, 5, 9, 2, 6]


In [101]:
# numpyの配列の末尾に一つ追加
pi_np = np.append(pi_np, 1)
# numpyの配列の末尾に配列を追加
pi_np = np.append(pi_np, [5, 9, 2, 6])
print(pi_np)

[3 1 4 1 5 9 2 6]


- 配列のソート

In [102]:
# Pythonの配列をソートして返す
pi_sorted = sorted(pi)
print(1, pi_sorted)
# 元の配列には変更なし
print(2, pi)
# Pythonの配列を直接ソートする
pi.sort()
print(3, pi)

1 [1, 1, 2, 3, 4, 5, 6, 9]
2 [3, 1, 4, 1, 5, 9, 2, 6]
3 [1, 1, 2, 3, 4, 5, 6, 9]


In [103]:
# numpyの配列のソート
pi_np_sorted = np.sort(pi_np)
print(1, pi_np_sorted)
# 元の配列には変更なし
print(2, pi_np)

1 [1 1 2 3 4 5 6 9]
2 [3 1 4 1 5 9 2 6]


- 列の切り出し

In [104]:
# numpyの2次元配列の作成(準備)
pi_np_2d = (pi_np[:6].reshape([2, 3]))
print(pi_np_2d)

[[3 1 4]
 [1 5 9]]


In [105]:
# Pythonの2次元配列の作成(準備)
pi_2d = pi_np_2d.tolist()
print(pi_2d)

[[3, 1, 4], [1, 5, 9]]


In [106]:
# numpyの2次元配列の列を取り出す
row0_np = pi_np_2d[:,0]
print(row0_np)

[3 1]


In [107]:
# Pythonの2次元配列の列を取り出す
# リスト内包表記を利用．pi_2dの各行から最初の要素を取り出し，リスト形式で渡す
row0 = [col[0] for col in pi_2d]
print(row0)

[3, 1]


## Numpy演習
1. numpy.arrayを用いて任意の2x3の行列を生成し，変数array1に格納せよ．
2. array1の形状を表示せよ．(printを使用)
3. numpy.random.randを用いて配列長100の乱数を生成し，変数array2に格納せよ．
4. スライスを用いて11〜20番目の要素を表示せよ．(indexに注意！)
5. numpy.sortとスライスを用いて，array2を降順にソートせよ．
6. array2中の各要素の2乗を計算し表示せよ．

### opencv

画像や動画の読み込み，編集，書き出し等を行うライブラリ

In [108]:
import cv2

サンプル画像(color.jpg)

![](color.jpg)

In [109]:
# 画像を読み込む
# RGBではなくBGRとして読み込まれることに注意
img = cv2.imread("color.jpg")

In [110]:
# 配列として読み込まれる
print(img)

[[[  0   0   0]
  [  0   0   0]
  [  1   1   1]
  ...
  [254 254 254]
  [255 255 255]
  [255 255 255]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [254 254 254]
  [255 255 255]
  [255 255 255]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [254 254 254]
  [255 255 255]
  [255 255 255]]

 ...

 [[  0   0 254]
  [  0   0 254]
  [  1   1 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0 254]
  [  0   0 254]
  [  1   1 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0 254]
  [  0   0 254]
  [  1   1 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [111]:
# 縦 x 横 x チャンネル
print(img.shape)

(400, 800, 3)


In [112]:
# 一番左上と右下の画素値を表示(BGR)
print(1, img[0, 0])
print(2, img[-1, -1])

1 [0 0 0]
2 [255 255 255]


画像の表示は
```python
cv2.imshow(window_name, image)
```
で行えるが， jupyter上では正しく表示できない．
matplotlibを用いると容易に表示できるが，
今回は授業の範囲を超えるので，
pyファイル(show_image.py)で実行する．