## Jupyter Notebook とは

webブラウザから使用できるインタラクティブなプログラムの実行環境
1. セル単位でプログラムを実行できる
2. インタラクティブに結果の可視化が行える
3. markdown記法にも対応していて，文書からコード，その実行結果まで一つのファイルで管理できる

In [1]:
print("Hello, world!")

Hello, world!


## Python の文法について

### 変数

- C言語では宣言文によって，変数のデータ型と名前を定義する必要がある. 例) `int x = 3;`
- pythonでは，変数に値を代入したタイミングで変数が定義される (型宣言をする必要がない)

In [2]:
x = 3
print(x)

3


In [3]:
# #でコメントアウトできる
# print文を書かなくても， セルの最後の行の変数や計算結果の値を確認できる
x + 3

6

### 変数の型
- int型 (整数)
- float型 (浮動小数点型)
- str型 (文字列型)
- bool型 (真偽値)

In [4]:
i = 4
print(type(i))

<class 'int'>


In [5]:
f = 2.1
print(type(f))

<class 'float'>


In [6]:
s = "Hello, world!"  # クオーテーションで囲う
print(type(s))

<class 'str'>


In [7]:
b = True
print(type(b))

<class 'bool'>


### 演算子
#### 代数演算子

- `+` 加算
- `-` 減算
- `*` 乗算
- `/` 除算
- `**` 冪乗
- `%` 余りを計算
- `//` 切り捨て

In [8]:
# 加算
2 + 3

5

In [9]:
# 減算
2 - 3

-1

In [10]:
# 乗算
2 * 3

6

In [11]:
# 除算
2 / 3

0.6666666666666666

In [12]:
# 冪乗
2 ** 3

8

In [13]:
# 余り
2 % 3

2

In [14]:
# 切り捨て
2 // 3

0

#### 代入演算子
- `a = b`
  aをbに代入
- `a += b`
  `a = a + b` と同じ
- `a -= b`
  `a = a - b` と同じ
- `a *= b`
  `a = a * b` と同じ
- `a /= b`
  `a = a / b` と同じ

In [15]:
a = 3
a = a + 3
print(a)

6


In [16]:
a = 3
a += 3
print(a)

6


#### 文字列演算
- `+` 文字列の連結
- `*` 文字列を定数回繰り返す

In [17]:
s1 = "Hello, "
s2 = "world! "
s = s1 + s2
print(s)

Hello, world! 


In [18]:
print(s * 10)

Hello, world! Hello, world! Hello, world! Hello, world! Hello, world! Hello, world! Hello, world! Hello, world! Hello, world! Hello, world! 


### 複合データ型
複数のデータをまとめて扱う
- `list` リスト
- `tuple` タプル
- `dict` 辞書

#### リスト
`[]`の中に複数の変数を`,`で区切って格納したもの

In [19]:
# リストを定義
numbers = [1, 2, 3, 4, 5]
print(numbers)

[1, 2, 3, 4, 5]


In [20]:
# 要素数の確認
len(numbers)

5

In [21]:
# list[インデックス] で各要素にアクセスできる
# 先頭が0から始まることに注意
numbers[0]

1

In [22]:
# インデックスを負の値にすると末尾からの位置になる
numbers[-1]

5

In [23]:
# 範囲外のインデックスを指定するとエラー
# pythonはエラー文が親切なので，しっかり読もう
numbers[100]

IndexError: list index out of range

In [24]:
# スライスを用いることで， リストから複数の値を取り出すことも
# list[開始位置:終了位置]
print(numbers[1:3])

[2, 3]


In [25]:
# 先頭や末尾のインデックスは省略できる
print(numbers[:3]) # numbers[0:3] と同じ
print(numbers[3:]) # numbers[3:5] と同じ

[1, 2, 3]
[4, 5]


In [26]:
# 要素を追加
numbers.append(6)
numbers

[1, 2, 3, 4, 5, 6]

In [113]:
# 2配列
numbers_2d = [[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]]
print(numbers_2d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


#### タプル
`()`の中に複数の変数を`,`区切りで格納したもの  
リストとの違いとして，一度定義したタプルは中身を変更することができない

In [27]:
assistants = ("ishikawa", "kobayashi")

In [28]:
# リストと同様に tuple[インデックス] で各要素にアクセスできる
assistants[0]

'ishikawa'

In [29]:
# タプルは途中で中身を変更できない
assistants[0] = "kasai"

TypeError: 'tuple' object does not support item assignment

#### 辞書型
キーとそれに対応する値を組み合わせて格納できる.  
`{key: value}`の形で書く.

In [30]:
grades = {"signal processing": "A", "LSI": "C", "Informatics engineering": "S"}

In [31]:
# dict[key] で 値を参照できる
grades["signal processing"]

'A'

In [32]:
# 値を入れ直すこともできる
grades["LSI"] = "D"
print(grades["LSI"])

D


In [33]:
# dict.keys() キーの一覧を取り出す
grades.keys()

dict_keys(['signal processing', 'LSI', 'Informatics engineering'])

In [34]:
# dict.values() 値の一覧を取り出す
grades.values()

dict_values(['A', 'D', 'S'])

In [35]:
# dict.items() キーと値の二つを取り出す
grades.items()

dict_items([('signal processing', 'A'), ('LSI', 'D'), ('Informatics engineering', 'S')])

### 制御構文

- 繰り返し (`for` `while`)
- 条件分岐 (`if` `else` `elif`)

C言語では，繰り返しの処理や条件分岐内の処理を`{}`で囲っていた
例)
```c
if (条件式) {
    なんらかの式
}
```

pythonはインデント記法を採用しているため, `{}`で囲う必要はなく，  
その代わり`:`とインデント(スペース)を用いてこれらの処理を書く

```python
if 条件式:
    なんらかの処理
```

#### for文

イテラブルオブジェクト(反復可能なオブジェクト)を用いた構文．  
listなどもイテラブルオブジェクトになる．
`range()`という組み込みの関数を使うと，  
指定した回数分の整数をもつイテラブルオブジェクトを作ってくれる
```python
for 変数 in イテラブルオブジェクト:
    なんらかの処理
```

In [36]:
# リストの要素を一つずつ取り出す
for i in [0, 1, 2, 3, 4]:
    print(i)

0
1
2
3
4


In [37]:
# range()関数を使うと，リストを手書きする必要がない
for i in range(5):
    print(i)

0
1
2
3
4


In [38]:
# (開始位置, 終了位置)も指定するすことができる
for i in range(10, 13):
    print(i)

10
11
12


In [39]:
# リストもイテラブルオブジェクト
prime_numbers = [2, 3, 4, 7, 11, 13, 17, 19]
for n in prime_numbers:
    print(n)

2
3
4
7
11
13
17
19


In [40]:
# rangeを使ってリストの中身を取り出すこともできる
N = len(prime_numbers)
for i in range(N):
    print(prime_numbers[i])

2
3
4
7
11
13
17
19


In [41]:
# dict.keys(), dict.values(), dict.items() もイテラブルオブジェクトを返している
grades = {"signal processing": "A", "LSI": "C", "Informatics engineering": "S"}
for key in grades.keys():
    print(key)

signal processing
LSI
Informatics engineering


In [42]:
for val in grades.values():
    print(val)

A
C
S


In [43]:
for key, val in grades.items():
    print(key, val)

signal processing A
LSI C
Informatics engineering S


#### if文

条件を満たしたかどうか(`True` or `False`)で処理を変えるための構文

```python
if 条件1:
    処理1  # 条件1を満たした時
elif 条件2:
    処理2  # 条件1を満たしていなく，かつ条件2を満たした時
else:
    処理3  # 条件1も条件2も満たしていない時
```


条件式の書き方．比較演算子とブール演算子を組み合わせて書く．
- 比較演算子
  - `a == b` aとbが等しい 
  - `a != b` aとbが異なる
  - `a < b` aがbよりも小さい
  - `a > b` aがbよりも大きい
  - `a >= b` aがb以上
  - `a <= b` aがb以下
  - `a in b` aがbに含まれる
- ブール演算子
  - `A and B` AとBが真なら真
  - `A or B` AかBが真なら真
  - `not A` Aが偽なら真

In [44]:
x = 10
if x >= 100:
    print("Too large")
elif x > 50:
    print("Large")
elif x == 50:
    print("Bingo!")
elif 10 <= x and x < 50:
    print("Small")
else:
    print("Too small")

Small


In [45]:
# 10 <= x and x < 50 の書き換え
x = 30
if 10 <= x < 50:
    print("True")

True


In [46]:
# in 演算子
x = 5
numbers = [1, 2, 3, 4, 5]
if x in numbers:
    print("True")
else:
    print("False")

True


#### while文

条件を満たしている間，ループし続ける．  
適切に条件を指定したり，終了条件を定めないと無限ループしてしまう
```python
while 条件式:
    処理
```

In [47]:
x = 0
while x < 10:
    x += 1
    print(x)

1
2
3
4
5
6
7
8
9
10


In [111]:
# 無限にループしてしまう！！  
# jupyter notebook中の停止ボタンで，セル内の処理を止めることができる
x = 0
while True:
   x += 1 

KeyboardInterrupt: 

In [49]:
# break 文を使ってループを抜けることができる
# whileやforの先頭に戻るcontinue文もある
x = 0
while True:
    x += 1
    if x >= 100:
        break
print(x)

100


In [50]:
# continue文の例
x = 0
y = 0
while True:
    x += 1
    
    if x % 3 != 0:
        continue
    
    y += 1
    
    if x >= 50:
        break

print("x", x)
print("y", y)

x 51
y 17


#### 演習1 FizzBuzz問題を解いてみよう
1から100までの数字を画面に表示する．  
その際に，数字が3の倍数の時は，数字の代わりに "Fizz"と出力する．
同様に5の倍数の時は，"Buzz"と出力し，
3の倍数でもあり5の倍数でもある時は"FizzBuzz"と出力しよう．


**期待する出力**
```
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
```

In [51]:
# write codes here


### 関数の定義

`def`を用いて関数を定義する．  
関数も`:`とインデントを用いる．
```python
def func(引数):
    処理
```

In [52]:
def double(x):
    print(2 * x)

In [53]:
double(10)

20


In [54]:
# 引数を複数指定することもできる
def add(x, y):
    print(x + y)

In [55]:
add(3, 2)

5


In [56]:
# 返り値は return で返すことができる
def add(x, y):
    return x + y 

In [57]:
result = add(10, 20)
print(result)

30


### クラス

例えば，青木研究室のメンバーの名簿を作ることを考える．  
それぞれのメンバーには苗字，名前，メールの情報を入れたい．
愚直に実装すると
```python
members = [
    {"first_name": "Yoshimitsu", "last_name": "Aoki", "email": "aoki@elec.keio.ac.jp"},
    {"first_name": "Yuchi", "last_name": "Ishikawa", "email": "aoki@elec.keio.ac.jp"},
    {"first_name": "Takuya", "last_name": "Kobayashi", "email": "aoki@elec.keio.ac.jp"},
]
```

となるが，各メンバーを構成する要素は同じ．  
-> 共通の設計図(クラス)を作ってあげると，各メンバーに属している変数(属性)や共通の振る舞い(メソッド)をもつ，メンバー(インスタンス)を作るのが簡単になる．

In [58]:
# クラスを定義
class Member:
    # インスタンス化する時に呼び出される関数
    # selfはインスタンス自身を表す
    def __init__(self, first_name, last_name, email):
        self.first_name = first_name 
        self.last_name = last_name
        self.email = email

In [59]:
aoki = Member(first_name="Yoshimitsu", last_name="Aoki", email="aoki@elec.keio.ac.jp")
print(aoki.first_name)
print(aoki.email)

Yoshimitsu
aoki@elec.keio.ac.jp


In [60]:
# クラスを定義
class Member:
    # インスタンス化する時に呼び出される関数
    # selfはインスタンス自身を表す
    def __init__(self, first_name, last_name, email):
        self.first_name = first_name 
        self.last_name = last_name
        self.email = email
    
    def self_introduction(self):
        print("Hi, there! I'm", self.first_name, self.last_name)

In [61]:
aoki = Member(first_name="Yoshimitsu", last_name="Aoki", email="aoki@elec.keio.ac.jp")
aoki.self_introduction()

Hi, there! I'm Yoshimitsu Aoki


In [62]:
kobayashi = Member(first_name="Takuya", last_name="Kobayashi", email="kobayashi@aoki-medialab.jp")
kobayashi.self_introduction()

Hi, there! I'm Takuya Kobayashi


## numpy
高速に配列計算を行うためのライブラリ

In [63]:
# ライブラリをインポート. numpyはnpとして扱うのが慣例
import numpy as np

In [64]:
# 1次元配列を作る
# np.array にリストを入れることで，1次元配列を定義できる
arr1 = np.array([1, 2, 3])
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [65]:
arr2 = np.array([4, 5, 6])

# もちろん演算も簡単にできる
print("足し算: ", arr1 + arr2)
print("引き算: ", arr1 - arr2)
print("直積: ", arr1 * arr2)
print("内積: ", np.dot(arr1, arr2))

足し算:  [5 7 9]
引き算:  [-3 -3 -3]
直積:  [ 4 10 18]
内積:  32


In [66]:
# 多次元配列を定義
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[4,5,6],[7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [67]:
# 形状を表示
print(arr3.shape)

(2, 3)


In [68]:
# 同様に演算ができる
print("足し算: ", arr3 + arr4)
print("引き算: ", arr3 - arr4)
print("直積: ", arr3 * arr4)

足し算:  [[ 5  7  9]
 [11 13 15]]
引き算:  [[-3 -3 -3]
 [-3 -3 -3]]
直積:  [[ 4 10 18]
 [28 40 54]]


In [69]:
# arr3 の列数と， arr4の行数が一致していないと内積は計算できない
# error!
np.dot(arr3, arr4)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [70]:
# 転置をしてから内積を取る
print(arr4.shape)
arr4_t = arr4.T
print(arr4_t.shape)

(2, 3)
(3, 2)


In [71]:
print(np.dot(arr3, arr4_t))

[[ 32  50]
 [ 77 122]]


#### ブロードキャスト
異なる形状の配列を計算する際に，一定のルールに基づいて形状が同じになるように自動で変換してくれる機能

具体的には以下のようなルールで実行される
- 次元数を揃える
  2つの配列の次元数が異なる場合、次元数が少ない方の配列の先頭にサイズ（長さ）が1の新しい次元を追加して次元数を揃える。
- 各次元のサイズ（長さ）を揃える
  2つの配列の各次元のサイズが一致しない場合、サイズが1である次元は他方の配列の次元のサイズに引き伸ばされる（値が繰り返される）。
- 2つの配列のどちらのサイズも1ではない次元が存在するとブロードキャストできずにエラーとなる。

In [72]:
arr5 = np.array([1, 2, 3])
arr6 = np.array([[5, 6, 7], [8, 9, 10]])

In [73]:
arr5 * 10

array([10, 20, 30])

In [74]:
arr5 * arr6

array([[ 5, 12, 21],
       [ 8, 18, 30]])

In [76]:
# ブロードキャストできない例
# error!
arr7 = np.array([2, 3])
arr5 * arr7

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [77]:
# インデックスを指定することで配列の一部を取り出せる
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
# 1行目を取り出す
print(arr[0])

[1 2 3]


In [79]:
# 1列目を取り出す
# [:]， は[0:]の省略
print(arr[:, 0])

[1 4 7]


In [80]:
# 2行3列目を取り出す
print(arr[1, 2])
print(arr[1][2])

6
6


#### np.where()
指定した条件を満たす配列内の要素のインデックスを見つけたり、特定の条件を満たす要素に新しい値を割り当てたりするのに役立つ

In [86]:
# 例: 1次元配列での利用
arr_1d = np.array([1, 2, 3, 4, 5])
print(np.where(arr_1d > 2))

(array([2, 3, 4]),)


In [88]:
# 例: 2次元配列での利用
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)
print(np.where(arr_2d > 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))


In [89]:
# 特定の条件を満たす要素に新しい値を割り当てる例
new_arr = np.where(arr > 2, 100, arr)
print(new_arr)

[  1   2 100 100 100]


In [91]:
# マスクの利用
mask = np.array([1, 1, 1, 0, 0, 0])
arr8 = np.array([8, 16, 24, 32, 40, 48])
arr9 = np.array([-9, -18, -27, -36, -45, -54])
masked = np.where(mask, arr8, arr9)
print(masked)

[  8  16  24 -36 -45 -54]


## opencv
画像や動画の読み込み，編集，書き出し等を行うライブラリ

In [92]:
import cv2

サンプル画像(color.jpg)

![](color.jpg)

In [96]:
# 画像を読み込む
# RGBではなくBGRとして読み込まれることに注意
img = cv2.imread("color.jpg")

In [97]:
# 配列として読み込まれる
print(img)

[[[  0   0   0]
  [  0   0   0]
  [  1   1   1]
  ...
  [254 254 254]
  [255 255 255]
  [255 255 255]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [254 254 254]
  [255 255 255]
  [255 255 255]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [254 254 254]
  [255 255 255]
  [255 255 255]]

 ...

 [[  0   0 254]
  [  0   0 254]
  [  1   1 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0 254]
  [  0   0 254]
  [  1   1 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0 254]
  [  0   0 254]
  [  1   1 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [100]:
# 縦 x 横 x チャンネル
print(img.shape)

(400, 800, 3)


In [110]:
# 一番左上の画素値を表示(BGR)
print(img[0, 0])

[0 0 0]
[255 255 255]


In [106]:
# データ型を表示
print(type(img[0, 0, 0]))

<class 'numpy.uint8'>


画像の表示は
```python
cv2.imshow(window_name, image)
```
で行えるが， jupyter上で実行するとバグる.  
matplotlibを用いると容易に表示できるが，
今回は授業の範囲を超えるので，
pyファイルで実行します